linters:
  # Disable all linters by default.
  disable-all: true

  # Enable specific linters.
  # Reference: https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # Default linters to enable
    - errcheck        # Checks for unchecked errors
    - gosimple        # Simplifies Go code
    - govet           # Detects suspicious constructs and possible errors
    - ineffassign     # Detects assignments to variables that are never used
    - staticcheck     # Performs advanced analysis on Go code
    - typecheck       # Ensures the correct usage of types
    - unused          # Detects unused variables, constants, functions, etc.

    # Additional linters to enable
    - gosec           # Security checker for Go code
    - forcetypeassert # Ensures type assertion is correct
    - noctx           # Warns when context is missing
    - unparam         # Detects function parameters that are not used
    - prealloc        # Suggests slice preallocation to improve performance

issues:
  # Define rules for excluding certain files or patterns
  exclude-rules:
    # Example: Exclude specific test functions in supervisor_testhelpers.go from the unused linter
    - path: pkg/supervisor/supervisor_testhelpers.go
      text: "^func.*supervisor.*(waitSettle|waitSettleError).*$"
      linters:
        - unused  # Do not report unused variables for these functions
